name: "Hello world"
description: "My first real add-on!"
version: "1.1.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  - RS485:
    type: Socket
  - Socket:
    server: 192.168.0.100
    port: 9999
schema:
  - RS485:
    type: str
  - Socket:
    server: str
    port: int